apiVersion: apps/v1
kind: Deployment
metadata:
  name: pymovies
  labels:
    app: pymovies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pymovies
  template:
    metadata:
      labels:
        app: pymovies
    spec:
      containers:
        - name: pymoviesapp
          # Pull from local docker registry
          image: pymovies:v1
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "20m"
              memory: "100Mi"
            requests:
              cpu: "10m"
              memory: "50Mi"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
